# Generated by Django 6.0 on 2026-01-06 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClusterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_id",
                    models.IntegerField(
                        help_text="Identificador único del cluster (0 a k-1)",
                        unique=True,
                        verbose_name="ID del Cluster",
                    ),
                ),
                (
                    "n_samples",
                    models.IntegerField(
                        help_text="Cantidad de muestras en este cluster",
                        verbose_name="Número de Muestras",
                    ),
                ),
                (
                    "categorical_modes",
                    models.JSONField(
                        default=dict,
                        help_text="Valores más comunes de variables categóricas",
                        verbose_name="Modas Categóricas",
                    ),
                ),
                (
                    "numeric_means",
                    models.JSONField(
                        default=dict,
                        help_text="Valores promedio de variables numéricas",
                        verbose_name="Promedios Numéricos",
                    ),
                ),
                (
                    "output_means",
                    models.JSONField(
                        default=dict,
                        help_text="Valores promedio de notas sensoriales",
                        verbose_name="Promedios de Notas",
                    ),
                ),
                (
                    "cluster_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo asignado manualmente (ej: 'Café Premium Alta Altitud')",
                        max_length=200,
                        verbose_name="Nombre del Cluster",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Información de Cluster",
                "verbose_name_plural": "Información de Clusters",
                "ordering": ["cluster_id"],
            },
        ),
        migrations.CreateModel(
            name="CoffeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del perfil (ej: 'Café Etíope Premium')",
                        max_length=200,
                        verbose_name="Nombre del Perfil",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del perfil",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(max_length=100, verbose_name="País de Origen"),
                ),
                (
                    "processing_method",
                    models.CharField(
                        max_length=100, verbose_name="Método de Procesamiento"
                    ),
                ),
                ("variety", models.CharField(max_length=100, verbose_name="Variedad")),
                (
                    "altitude_mean",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="Altitud Promedio (metros)",
                    ),
                ),
                (
                    "moisture",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Humedad",
                    ),
                ),
                (
                    "category_one_defects",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Defectos Categoría 1",
                    ),
                ),
                (
                    "category_two_defects",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Defectos Categoría 2",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el perfil está activo",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Café",
                "verbose_name_plural": "Perfiles de Café",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        help_text="País donde se cultivó el café (ej: Ethiopia, Brazil)",
                        max_length=100,
                        verbose_name="País de Origen",
                    ),
                ),
                (
                    "processing_method",
                    models.CharField(
                        help_text="Método usado para procesar el café (ej: Washed / Wet, Natural / Dry)",
                        max_length=100,
                        verbose_name="Método de Procesamiento",
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        help_text="Variedad del café (ej: Bourbon, Typica, Caturra)",
                        max_length=100,
                        verbose_name="Variedad",
                    ),
                ),
                (
                    "altitude_mean",
                    models.FloatField(
                        help_text="Altitud promedio donde se cultivó el café",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="Altitud Promedio (metros)",
                    ),
                ),
                (
                    "moisture",
                    models.FloatField(
                        help_text="Nivel de humedad del café (0.0 a 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Humedad",
                    ),
                ),
                (
                    "category_one_defects",
                    models.IntegerField(
                        default=0,
                        help_text="Número de defectos primarios",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Defectos Categoría 1",
                    ),
                ),
                (
                    "category_two_defects",
                    models.IntegerField(
                        default=0,
                        help_text="Número de defectos secundarios",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Defectos Categoría 2",
                    ),
                ),
                (
                    "cluster_asignado",
                    models.IntegerField(
                        help_text="ID del cluster K-means al que fue asignado",
                        verbose_name="Cluster Asignado",
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        help_text="Porcentaje de confianza de la predicción (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Confianza (%)",
                    ),
                ),
                (
                    "distancia_centroide",
                    models.FloatField(
                        help_text="Distancia euclidiana al centroide del cluster",
                        verbose_name="Distancia al Centroide",
                    ),
                ),
                (
                    "aroma",
                    models.FloatField(
                        help_text="Nota de aroma predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Aroma",
                    ),
                ),
                (
                    "flavor",
                    models.FloatField(
                        help_text="Nota de sabor predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Sabor",
                    ),
                ),
                (
                    "aftertaste",
                    models.FloatField(
                        help_text="Nota de retrogusto predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Retrogusto",
                    ),
                ),
                (
                    "acidity",
                    models.FloatField(
                        help_text="Nota de acidez predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Acidez",
                    ),
                ),
                (
                    "body",
                    models.FloatField(
                        help_text="Nota de cuerpo predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Cuerpo",
                    ),
                ),
                (
                    "balance",
                    models.FloatField(
                        help_text="Nota de balance predicha (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "total_cup_points",
                    models.FloatField(
                        help_text="Puntuación total de la taza (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Puntos Totales",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se realizó la predicción",
                        verbose_name="Fecha de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción",
                "verbose_name_plural": "Predicciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="cafe_app_pr_created_20657a_idx"
                    ),
                    models.Index(
                        fields=["cluster_asignado"],
                        name="cafe_app_pr_cluster_bd1da6_idx",
                    ),
                ],
            },
        ),
    ]
